steps:
  # Build the client image
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '-t', 'gcr.io/$_PROJECT_ID/$_SERVICE_NAME:latest',
      '-t', 'gcr.io/$_PROJECT_ID/$_SERVICE_NAME:$BUILD_ID',
      '-f', 'client/Dockerfile',
      'client'
    ]

  # Push the image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$_PROJECT_ID/$_SERVICE_NAME:latest']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$_PROJECT_ID/$_SERVICE_NAME:$BUILD_ID']

# Store images in Google Container Registry
images:
  - 'gcr.io/$_PROJECT_ID/$_SERVICE_NAME:latest'
  - 'gcr.io/$_PROJECT_ID/$_SERVICE_NAME:$BUILD_ID'

# Build options
options:
  machineType: 'E2_HIGHCPU_8'
  diskSizeGb: 100
  logging: CLOUD_LOGGING_ONLY

# Substitutions
substitutions:
  _SERVICE_NAME: 'tcg-marketplace-client'
  _PROJECT_ID: 'fourth-arena-474414-h6'

