# Use a modern version of the Docker Compose file format
version: '3.8'

services:
  # The React Client Service
  client:
    build: ./client
    container_name: client
    ports:
      - "5173:5173" # Map the Vite dev server port
    volumes:
      - ./client:/app # Mount local code into the container
      - /app/node_modules # Anonymous volume to prevent local node_modules from overwriting the container's
    depends_on:
      - server # The client depends on the server being available
    stdin_open: true # Necessary for Vite's interactive terminal
    tty: true

  # The Node.js Server Service
  server:
    build: ./server
    container_name: server
    ports:
      - "5000:5000" # Map the server's API port
    volumes:
      - ./server:/app
      - /app/node_modules
    environment:
      # Connection string for MongoDB. It uses the service name 'mongo' as the hostname.
      # IMPORTANT: Replace the username and password with your own credentials.
      MONGO_URI: mongodb://your_mongo_user:your_mongo_password@mongo:27017/yugioh_db?authSource=admin
    depends_on:
      - mongo # The server depends on the database being available

  # The MongoDB Database Service
  mongo:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017" # Map the MongoDB port
    volumes:
      - mongo-data:/data/db # Use a named volume to persist database data
    environment:
      # IMPORTANT: Set your desired root username and password for the database.
      MONGO_INITDB_ROOT_USERNAME: your_mongo_user
      MONGO_INITDB_ROOT_PASSWORD: your_mongo_password

# Define the named volume for data persistence
volumes:
  mongo-data: