apiVersion: apps/v1
kind: Deployment
metadata:
  name: tcg-market-client
  namespace: tcg-market
  labels:
    app: tcg-market-client
spec:
  replicas: 2
  selector:
    matchLabels:
      app: tcg-market-client
  template:
    metadata:
      labels:
        app: tcg-market-client
    spec:
      containers:
      - name: client
        image: tcg-market-client:latest
        ports:
        - containerPort: 80
        env:
        - name: VITE_API_URL
          valueFrom:
            configMapKeyRef:
              name: tcg-market-config
              key: VITE_API_URL
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "250m"
        livenessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5
