# Kubeconfig template
# Copy this file to ~/.kube/config or set KUBECONFIG environment variable
# Replace the values below with your actual cluster configuration

apiVersion: v1
kind: Config
clusters:
- cluster:
    server: https://your-cluster-endpoint:6443
    certificate-authority-data: your-ca-certificate-data
  name: your-cluster-name
contexts:
- context:
    cluster: your-cluster-name
    user: your-user-name
  name: your-context-name
current-context: your-context-name
users:
- name: your-user-name
  user:
    client-certificate-data: your-client-certificate-data
    client-key-data: your-client-key-data
