apiVersion: apps/v1
kind: Deployment
metadata:
  name: tcg-market-server
  namespace: tcg-market
  labels:
    app: tcg-market-server
spec:
  replicas: 2
  selector:
    matchLabels:
      app: tcg-market-server
  template:
    metadata:
      labels:
        app: tcg-market-server
    spec:
      containers:
      - name: server
        image: tcg-market-server:latest
        ports:
        - containerPort: 5000
        env:
        - name: NODE_ENV
          valueFrom:
            configMapKeyRef:
              name: tcg-market-config
              key: NODE_ENV
        - name: PORT
          valueFrom:
            configMapKeyRef:
              name: tcg-market-config
              key: PORT
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /api/health
            port: 5000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /api/health
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 5
