apiVersion: v1
kind: Service
metadata:
  name: tcg-market-server
  namespace: tcg-market
  labels:
    app: tcg-market-server
spec:
  selector:
    app: tcg-market-server
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
  type: ClusterIP
