name: Build and Deploy to GKE

on:
  push:
    branches:
      - main

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Server Dependencies and Test
        run: |
          echo "--- Testing Server ---"
          cd server
          npm install
          npm test

      - name: Install Client Dependencies and Test
        run: |
          echo "--- Testing Client ---"
          cd client
          npm install
          npm test

      - name: Install Worker Dependencies and Test
        run: |
          echo "--- Testing Worker ---"
          cd worker
          npm install
          npm test

  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    needs: test # This job will only run if the 'test' job succeeds

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - id: 'auth'
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v1'

      - name: 'Authorize Docker push'
        run: gcloud auth configure-docker us-central1-docker.pkg.dev

      - name: Build and Deploy Script
        run: |
          chmod +x ./deployment/build-deploy-gcp.sh
          ./deployment/build-deploy-gcp.sh
          